- config: mangalia
  uavs: 
    - hector
  uav_waypoints:
# hold_time in second, rel_alt is height above ground 
# Please see Waypoint.msg in mavros_msgs package for other parameters
      - {hold_time: 2.0, radius: 1.0, yaw: 0.0, lat: 43.7993805, long: 28.5936459, rel_alt:  40.0, inspect: False}
      - {hold_time: 5.0, radius: 1.0, yaw: 0.0, lat: 43.7993805, long: 28.5936459, rel_alt:  100.0, inspect: True}
  asvs:
    - halcyon
  uav_carrier: halcyon
  asv_waypoints:
    - {hold_time: 2.0, radius: 2.0, yaw: 0.0, lat: 43.799513, long: 28.594846, takeoff: False}
    - {hold_time: 2.0, radius: 2.0, yaw: 0.0, lat: 43.799336, long: 28.593810, takeoff: True}
    - {hold_time: 5.0, radius: 2.0, yaw: 0.0, lat: 43.799164, long: 28.594843, takeoff: False}
- config: asv_mangalia
  uavs: [] 
  uav_waypoints: []
  asvs:
    - halcyon
  uav_carrier: halcyon
  asv_waypoints:
    - {hold_time: 2.0, radius: 2.0, yaw: 0.0, lat: 43.799513, long: 28.594846, takeoff: False}
    - {hold_time: 2.0, radius: 2.0, yaw: 0.0, lat: 43.799336, long: 28.593810, takeoff: True}
    - {hold_time: 5.0, radius: 2.0, yaw: 0.0, lat: 43.799164, long: 28.594843, takeoff: False}
- config: uav_mangalia
  uavs: 
    - hector
  uav_waypoints:
      - {hold_time: 2.0, radius: 1.0, yaw: 0.0, lat: 43.7993805, long: 28.5936459, rel_alt:  40.0, inspect: False}
      - {hold_time: 5.0, radius: 1.0, yaw: 0.0, lat: 43.7993805, long: 28.5936459, rel_alt:  100.0, inspect: True}
  asvs: []
  uav_carrier: '' 
  asv_waypoints: []
